<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Core\Configure;
use Cake\Core\Exception\Exception;
use Cake\Datasource\ConnectionManager;
use Cake\ORM\TableRegistry;
use Phinx\Config\Config;

/**
 * CitizenCorner Controller
 *
 * @property \App\Model\Table\CitizenCornerTable $CitizenCorner
 */
class ReportleaveController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Auth->allow();
        $this->loadComponent('RequestHandler');

    }

    /**
     * Index method
     *
     * @return void
     */
    public function index()
    {
        if ($this->request->is('post')) {
            $start_date = strtotime($this->request->data['from_date']);
            $end_date = strtotime($this->request->data['to_date']);

            $leaves = TableRegistry::get('applications')->find();
        //    $leaves->select(['applications.id', 'applications.application_type_id', 'applications.applicant_name_bn', 'applications.phone', 'applications.email', 'applications.start_date', 'applications.end_date']);

            if (!empty($start_date) && $start_date > 0) {
                $leaves->where(['start_date  >=' => $start_date]);
            }
            if (!empty($end_date) && $end_date > 0) {
                $leaves->where(['end_date  <=' => $end_date]);
            }
            $leaves->contain(['LocationTypes']);
            $leaves->contain(['ApplicationTypes']);

            $reportData = $leaves->toArray();
         //   echo "<pre/>"; print_r($reportData);die();
            $this->set('reportData', $reportData);
            $this->set('_serialize', ['reportData']);
        }




    }


}
